import { GoogleOAuthProvider, GoogleLogin } from "@react-oauth/google";
import "bootstrap/dist/css/bootstrap.css"
import styles from "./globals.module.css"
import type { Metadata } from "next";
import envConfig from "./env.config";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>){
      return (
        <html className={styles.html} lang="en">
          <GoogleOAuthProvider clientId={envConfig.googleClientId}>
            <body>{children}</body>
          </GoogleOAuthProvider>
        </html>
      );
    }