import { GoogleOAuthProvider, GoogleLogin } from "@react-oauth/google";
import "bootstrap/dist/css/bootstrap.css"
import styles from "./main.module.css"
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "SicnecherChat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>){
      return (
        <html className={styles.html} lang="en">
            <body>{children}</body>
        </html>
      );
    }